config/routes.rb
ReleaseNotes::Engine.routes.draw do

  resources :release_notes, path: '/' do
    member do
      get :publish_toggle
      get :notify
      get :enhancements
      get :bug_fixes
    end


    get "new_features", to: "release_notes#new_features"
    get "enhancements", to: "release_notes#enhancements"
    get "bug_fixes", to: "release_notes#bug_fixes"
  end

end

app/models/release_notes/application_record.rb
module ReleaseNotes
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/release_notes/change_type.rb
module ReleaseNotes
  class ChangeType < ApplicationRecord
    has_many :release_note_items, class_name: 'ReleaseNotes::ReleaseNoteItem'

    validates :name, :icon, presence: true
    validates :priority, presence: true, uniqueness: true
  end
end

app/models/release_notes/release_note.rb
module ReleaseNotes
  class ReleaseNote < ApplicationRecord
    has_many :release_note_items, class_name: 'ReleaseNotes::ReleaseNoteItem'

    # This belongs_to references the user_klass config variable, as set in the main app Release Notes initializer file.
    # This will likely be: /config/initializers/release_notes.rb
    belongs_to :user, class_name: ReleaseNotes.user_klass.to_s, foreign_key: :user_id  if ReleaseNotes.user_klass.to_s.constantize.is_a?(Class) rescue false

    accepts_nested_attributes_for :release_note_items, allow_destroy: true, reject_if: :all_blank

    validates :release_date, :title, :user_id, :presence => true

    scope :published, -> {where(published: true)}
    scope :bug_fixes, -> {joins(release_note_items: :change_type).where("release_notes_change_types.name = 'Bug Fix'")}
    scope :new_features, -> {joins(release_note_items: :change_type).where("release_notes_change_types.name = 'New Feature'")}
    scope :enhancements, -> {joins(release_note_items: :change_type).where("release_notes_change_types.name = 'Enhancement'")}
  end
end

app/models/release_notes/release_note_item.rb
module ReleaseNotes
  class ReleaseNoteItem < ApplicationRecord
    belongs_to :release_note, class_name: 'ReleaseNotes::ReleaseNote'
    belongs_to :change_type, class_name: 'ReleaseNotes::ChangeType'
    # This belongs_to references the user_klass config variable, as set in the main app Release Notes initializer file.
    # This will likely be: /config/initializers/release_notes.rb
    belongs_to :user, class_name: ReleaseNotes.user_klass.to_s, foreign_key: :user_id if ReleaseNotes.user_klass.to_s.constantize.is_a?(Class) rescue false

    validates :change_type, :change_title, :change_details, :user_id, :release_note, :presence => true

    scope :bug_fix, -> {where("change_type_id IN (SELECT id FROM release_notes_change_types WHERE (name = 'Bug Fix'))")}
    scope :new_feature, -> {where("change_type_id IN (SELECT id FROM release_notes_change_types WHERE (name = 'New Feature'))")}
    scope :enhancement, -> {where("change_type_id IN (SELECT id FROM release_notes_change_types WHERE (name = 'Enhancement'))")}

  end
end

app/controllers/release_notes/application_controller.rb
module ReleaseNotes
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/release_notes/release_note_items_controller.rb
require_dependency "release_notes/application_controller"

module ReleaseNotes
  class ReleaseNoteItemsController < ApplicationController
    before_action :set_release_note_item, only: [:edit, :update, :destroy]

    def new
      @release_note_item = ReleaseNoteItem.new
    end

    def create
      @release_note_item = ReleaseNoteItem.new(release_note_item_params)
      @release_note_item.save!
    end

    def edit
    end

    def update
      @release_note_item.update(release_note_item_params)
    end

    def destroy

    end

    private

    def set_release_note_item
      @release_note_item = ReleaseNoteItem.find(params[:id])
      puts 'Working on Release Note Item ' + @release_note_item.id.to_s
    end

    def release_note_item_params
      params.require(:release_note).permit(:id, :release_note_id, :change_type_id, :change_title, :change_details, :_destroy)
    end

  end
end

app/controllers/release_notes/release_notes_controller.rb
require_dependency "release_notes/application_controller"

module ReleaseNotes
  class ReleaseNotesController < ApplicationController
    before_action :set_release_note, only: [:show, :edit]

    def index
      @release_notes = ReleaseNote.all
    end

    def new
      @release_note = ReleaseNote.new
      @release_note.release_note_items.build
    end

    def create
      @release_note = ReleaseNote.new(release_note_params)

      begin
        if @release_note.save!
          respond_to do |format|
            flash[:notice] = 'Release Note created'
            format.html {redirect_to @release_note}
          end
        end
      rescue ActiveRecord::RecordInvalid => invalid
        respond_to do |format|
          format.html {render new_release_note_path}
        end
      end

    end

    def update
      release_note = set_release_note
      if release_note.update(release_note_params)
        respond_to do |format|
          flash[:notice] = 'Release Note updated'
          format.html {redirect_to @release_note}
        end
      end
    end

    def show
    end

    def edit
    end

    def destroy
      release_note = set_release_note
      release_note.release_note_items.each do |rni|
        rni.destroy
      end
      if release_note.destroy
        respond_to do |format|
          flash[:notice] = 'Release Note deleted'
          format.html {redirect_to :release_notes}
        end
      end
    end

    def publish_toggle
      release_note = set_release_note
      if release_note.published
        if release_note.update(published: false)
          respond_to do |format|
            flash[:notice] = 'Release Note unpublished'
            format.html {redirect_to :release_notes}
          end
        end
      else
        if release_note.update(published: true)
          respond_to do |format|
            flash[:notice] = 'Release Note published'
            format.html {redirect_to :release_notes}
          end
        end
      end
    end

    def tim_rn_signature
      sig = ENV['TIM_RN_RELEASE_NOTES_KEY']
      Obfuscate.new.encrypt(sig)
    end

    def notify
      release_note = set_release_note
      through_link = ENV['TIM_RELEASE_NOTES_URL'] + "/release_notes/" + release_note.id.to_s

      domains = ENV['WEBHOOK_URLS'].split(',')
      domains.each do |domain|

        puts "## Domain: #{domain}"

        url = URI.parse(domain)
        req = Net::HTTP::Post.new(url.request_uri, 'Content-Type' => 'application/json', 'x-tim-release-note' => tim_rn_signature)
        req.body = {origin: "TIM-Release-Notes", title: release_note.title, rnid: release_note.id, icon_emoji: ":beers:", text: "*There's a new version of TIM!*", "attachments": [{"actions": [{"type": "button", "text": release_note.title, "url": through_link}]}]}.to_json
        http = Net::HTTP.new(url.host, url.port)
        http.use_ssl = (url.scheme == "https")
        response = http.request(req)

        puts "## Request: #{req.body}"
        puts "## Response: #{response.body}"

      end

      notifier = Slack::Notifier.new ReleaseNotes.config.slack_hook

      attachment_payload = {
          "fields": [
              {
                  "title": "There's a new version of TIM!",
                  "value": "Have a read through the release notes:\n<#{through_link} |#{release_note.title}>",
                  "short": false
              }
          ]
      }
      notifier.post icon_emoji: ":beers:", attachments: [attachment_payload]

      respond_to do |format|
        flash[:notice] = 'Notification Sent'
        format.html {redirect_to :release_notes}
      end
    end

    def new_features
      @release_notes = ReleaseNote.new_features
    end

    def enhancements
      @release_notes = ReleaseNote.enhancements
    end

    def bug_fixes
      @release_notes = ReleaseNote.bug_fixes
    end

    private

    def set_release_note
      @release_note = ReleaseNote.find(params[:id])
    end

    def release_note_params
      params.require(:release_note).permit(:id, :user_id, :title, :intro, :outro, :release_date, :published,
                                           release_note_items_attributes: [:id, :user_id, :release_note_id, :change_type_id, :change_title, :change_details, :_destroy])
    end
  end
end

app/helpers/release_notes/application_helper.rb
module ReleaseNotes
  module ApplicationHelper

    def dev_user(id = current_user.id)
      [4, 116, 262].include?(id)
    end

  end
end

app/helpers/release_notes/obfuscate.rb
require 'openssl'
require 'base64'
module ReleaseNotes
  class Obfuscate
    def self.included(base)
      base.extend self
    end

    def decrypt(value)
      begin
        c = cipher.decrypt
        c.key = Digest::SHA256.digest(cipher_key)
        c.update(Base64.decode64(value.to_s)) + c.final
      rescue
        return
      end

    end

    def encrypt(value)
      c = cipher.encrypt
      c.key = Digest::SHA256.digest(cipher_key)
      Base64.encode64(c.update(value.to_s) + c.final)
    end

    private

    def cipher
      OpenSSL::Cipher::Cipher.new('aes-256-cbc')
    end

    def cipher_key
      'K3ep1ng_It-Reel!'
    end

  end
end

app/views/release_notes/release_notes/_left_menu.html.erb
<div class="index-menu">

  <% if user_signed_in? && dev_user %>

    <% @release_notes.order(release_date: :desc).map {|d| d.release_date.year}.uniq.each do |year| %>
      <ul class="nav nav-list">

        <li class="nav-header index-menu-year">
          <span><%= year %></span>
          <ul class="nav nav-list flex-column index-menu-month" id="<%= year %>">
            <% @release_notes.order(release_date: :desc).where('extract(year from release_date) = ?', year).map {|d| d.release_date.month}.uniq.each do |month| %>

              <li class="nav-item">
                <%= link_to t('date.month_names')[month], '#' + t('date.month_names')[month] + '-' + year.to_s %>
              </li>

            <% end %>
          </ul>
        </li>

      </ul>
    <% end %>

  <% else %>

    <% @release_notes.published.select("release_date").order(release_date: :desc).map {|d| d.release_date.year}.uniq.each do |year| %>
      <ul class="nav nav-list">

        <li class="nav-header index-menu-year">
          <span><%= year %></span>
          <ul class="nav nav-list flex-column index-menu-month" id="<%= year %>">
            <% @release_notes.published.order(release_date: :desc).where('extract(year from release_date) = ?', year).map {|d| d.release_date.month}.uniq.each do |month| %>

              <li class="nav-item">
                <%= link_to t('date.month_names')[month], '#' + t('date.month_names')[month] + '-' + year.to_s %>
              </li>

            <% end %>
          </ul>
        </li>

      </ul>
    <% end %>

  <% end %>
</div>

app/views/release_notes/release_notes/_no_release_notes.html.erb
<div class="release-note-container">
  <div class="center">Uh-oh! There are no release notes yet <i class="far fa-frown"></i></div>
  <% if user_signed_in? %>
    <div class="center">
      <br/><%= link_to 'Add a Release Note', new_release_note_path, class: 'btn btn-sm btn-primary' %></div>
  <% end %>
</div>

app/views/release_notes/release_notes/_release_note.html.erb
<div class="anchor" id="<%= t('date.month_names')[release_note.release_date.month] + '-' + release_note.release_date.year.to_s %>"></div>
<div class="release-note-container">

  <div class="release-note-row">
    <div class="release-note-title">
      <%= release_note.title %>
    </div>
  </div>
  <div class="release-note-row">
    <div class="release-note-date">
      <%= release_note.release_date.strftime("#{release_note.release_date.day.ordinalize} %B %Y") %>
    </div>
  </div>

  <div class="release-note-row">
    <div class="release-note-intro">
      <%= release_note.intro.html_safe %>
    </div>
  </div>

  <div class="release-note-items">

    <% release_note.release_note_items.joins(:change_type).order("priority").map(&:change_type_id).uniq.each do |type| %>

      <% release_note_items = release_note.release_note_items.where("change_type_id = ?", type) %>
      <% change_type_name = release_note_items.first.change_type.name %>
      <% auto_show = shown_type == 'all' || shown_type == change_type_name %>

      <button class="release-note-type collapsible">
        <span class="fa-stack">
          <i class="fa <%= release_note_items.first.change_type.icon %> fa-stack-2x"></i>
        </span>
        <%= change_type_name.pluralize(release_note_items.count) %>
        <span class="indicator pull-right"><%= auto_show ? '-' : '+' %></span>
      </button>

      <div class="content" style="<%= auto_show ? 'display:block' : 'display:none' %>">
        <% release_note_items.each do |item| %>

          <div class="release-note-item-row">
            <div class="release-note-item-icon">
              <i class="fa <%= item.change_type.icon %>"></i>
            </div>
            <div class="release-note-item-col">
              <div class="release-note-item-title">
                <%= item.change_title %>
              </div>
              <div class="release-note-item-details">
                <%= item.change_details.html_safe %>
              </div>
            </div>
          </div>

        <% end %>
      </div>

    <% end %>

  </div>

  <div class="release-note-row">
    <div class="release-note-outro">
      <%= release_note.outro.html_safe %>
    </div>
  </div>

  <div class="release-note-row">
    <div class="release-note-signed-by">
      <hr/>
      <%= release_note.user.full_name %>
    </div>
  </div>

  <% if user_signed_in? && dev_user %>
    <div class="release-note-row">
      <div class="release-note-buttons">
        <% if release_note.published %>
          <%= link_to 'Notify', notify_release_note_path(id: release_note.id), class: 'btn btn-sm btn-success' %>
          <%= link_to 'Unpublish', publish_toggle_release_note_path(id: release_note.id), class: 'btn btn-sm btn-danger' %>
        <% else %>
          <%= link_to 'Edit', edit_release_note_path(id: release_note.id), class: 'btn btn-sm btn-info' %>
          <%= link_to 'Publish', publish_toggle_release_note_path(id: release_note.id), class: 'btn btn-sm btn-success' %>
          <%= link_to 'Delete', release_note_path(release_note), :method => :delete, data: {confirm: t('deletion.confirm_text'), afirm: t('button_labels.confirm'), cancel: t('button_labels.cancel')}, class: 'action-link btn btn-md btn-danger' %>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/release_notes/release_notes/_release_note_form.html.erb
<div class="release-note-container">

  <%= simple_form_for(@release_note, html: {class: 'form'}) do |f| %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="release-note-row">
      <div class="release-note-title">
        <%= f.input :title, html: {class: 'form-control input-sm wide-string-input'} %>
      </div>
    </div>

    <div class="release-note-row">
      <div class="release-note-date">
        <%= f.input :release_date, as: :date, html5: true, html: {class: 'form-control input-sm'} %>
      </div>
    </div>

    <%= f.input :intro, label: 'Intro (HTML safe)' %><br/>

    Release Note Items:
    <div class="release-note-items-form">
      <%= f.simple_fields_for :release_note_items do |rni| %>
        <%= render 'release_notes/release_notes/release_note_item_form', f: rni %>
      <% end %>
      <div>
        <%= link_to_add_association f, :release_note_items, partial: 'release_notes/release_notes/release_note_item_form' do %>
          <i class="fa fa-plus-square add"></i>
        <% end %>
      </div>

    </div>
    <%= f.input :outro, label: 'Outro (HTML safe)' %><br/>
    <%= f.button :submit, class: 'btn btn-sm btn-primary' %>
  <% end %>

</div>

app/views/release_notes/release_notes/_release_note_item_form.erb
<div class="release-note-type release-note-item-form-container nested-fields">
  <%= f.hidden_field :release_note_id, value: f.object.release_note.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="release-note-item-form-change-type">
    <%= f.input :change_type_id, label: 'Change Type', collection: ReleaseNotes::ChangeType.all, allow_blank: false, html: {class: 'form-control input-sm'} %>
  </div>

  <div class="release-note-item-form-change-title">
    <%= f.input :change_title, label: 'Change Title', html: {class: 'form-control input-sm'} %>
  </div>


  <div class="release-note-item-form-change-details">
    <%= f.input :change_details, label: 'Change Details (HTML safe)', html: {class: 'form-control input-sm'} %>
  </div>

  <div class="release-note-item-add-button">
    <%= link_to_remove_association f do %>
      <i class="fa fa-trash delete"></i>
    <% end %>
  </div>

</div>

app/views/release_notes/release_notes/bug_fixes.html.erb
<div class="index-container">

  <!-- Left Menu -->
  <%= render 'release_notes/release_notes/left_menu' %>

  <!-- Articles -->
  <div class="index-articles">
    <% if user_signed_in? && dev_user %>
      <% if @release_notes.count > 0 %>
        <% @release_notes.order(release_date: :desc, id: :desc).uniq.each do |note| %>

          <%= render partial: 'release_notes/release_notes/release_note', locals: {release_note: note, shown_type: 'Bug Fix'} %>

        <% end %>
      <% else %>

        <%= render 'release_notes/release_notes/no_release_notes' %>

      <% end %>

    <% else %>

      <% if @release_notes.published.count > 0 %>
        <% @release_notes.published.order(release_date: :desc, id: :desc).uniq.each do |note| %>

          <%= render partial: 'release_notes/release_notes/release_note', locals: {release_note: note, shown_type: 'Bug Fix'} %>

        <% end %>
      <% else %>

        <%= render 'release_notes/release_notes/no_release_notes' %>

      <% end %>

    <% end %>
  </div>

</div>

app/views/release_notes/release_notes/edit.html.erb
<%= render 'release_notes/release_notes/release_note_form' %>

app/views/release_notes/release_notes/enhancements.html.erb
<div class="index-container">

  <!-- Left Menu -->
  <%= render 'release_notes/release_notes/left_menu' %>

  <!-- Articles -->
  <div class="index-articles">
    <% if user_signed_in? && dev_user %>
      <% if @release_notes.count > 0 %>
        <% @release_notes.order(release_date: :desc, id: :desc).uniq.each do |note| %>

          <%= render partial: 'release_notes/release_notes/release_note', locals: {release_note: note, shown_type: 'Enhancement'} %>

        <% end %>
      <% else %>

        <%= render 'release_notes/release_notes/no_release_notes' %>

      <% end %>

    <% else %>

      <% if @release_notes.published.count > 0 %>
        <% @release_notes.published.order(release_date: :desc, id: :desc).uniq.each do |note| %>

          <%= render partial: 'release_notes/release_notes/release_note', locals: {release_note: note, shown_type: 'Enhancement'} %>

        <% end %>
      <% else %>

        <%= render 'release_notes/release_notes/no_release_notes' %>

      <% end %>

    <% end %>
  </div>

</div>

app/views/release_notes/release_notes/index.html.erb
<div class="index-container">

  <!-- Left Menu -->
  <%= render 'release_notes/release_notes/left_menu' %>

  <!-- Articles -->
  <div class="index-articles">
    <% if user_signed_in? && dev_user %>
      <% if @release_notes.count > 0 %>
        <% @release_notes.order(release_date: :desc, id: :desc).each do |note| %>

          <%= render partial: 'release_notes/release_notes/release_note', locals: {release_note: note, shown_type: 'all'} %>

        <% end %>
      <% else %>

        <%= render 'release_notes/release_notes/no_release_notes' %>

      <% end %>

    <% else %>

      <% if @release_notes.published.count > 0 %>
        <% @release_notes.published.order(release_date: :desc, id: :desc).each do |note| %>

          <%= render partial: 'release_notes/release_notes/release_note', locals: {release_note: note, shown_type: 'all'} %>

        <% end %>
      <% else %>

        <%= render 'release_notes/release_notes/no_release_notes' %>

      <% end %>

    <% end %>
  </div>

</div>

app/views/release_notes/release_notes/new.html.erb
<%= render 'release_notes/release_notes/release_note_form' %>

app/views/release_notes/release_notes/new_features.html.erb
<div class="index-container">

  <!-- Left Menu -->
  <%= render 'release_notes/left_menu' %>

  <!-- Articles -->
  <div class="index-articles">
    <% if user_signed_in? && dev_user %>
      <% if @release_notes.count > 0 %>
        <% @release_notes.order(release_date: :desc, id: :desc).uniq.each do |note| %>

          <%= render partial: 'release_notes/release_notes/release_note', locals: {release_note: note, shown_type: 'New Feature'} %>

        <% end %>
      <% else %>

        <%= render 'release_notes/release_notes/no_release_notes' %>

      <% end %>

    <% else %>

      <% if @release_notes.published.count > 0 %>
        <% @release_notes.published.order(release_date: :desc, id: :desc).uniq.each do |note| %>

          <%= render partial: 'release_notes/release_notes/release_note', locals: {release_note: note, shown_type: 'New Feature'} %>

        <% end %>
      <% else %>

        <%= render 'release_notes/release_notes/no_release_notes' %>

      <% end %>

    <% end %>
  </div>

</div>

app/views/release_notes/release_notes/show.html.erb
<!-- Left Menu -->
<div class="index-menu">

  <ul class="nav nav-list">

    <li class="nav-header index-menu-year">
      <ul class="nav nav-list flex-column index-menu-month" id="show_all">
        <li class="nav-item">
          <%= link_to 'Show All', release_notes_path %>
        </li>
      </ul>
    </li>

  </ul>
</div>

<%= render partial: 'release_notes/release_notes/release_note', locals: {release_note: @release_note, shown_type: 'all'} %>